name: "UDP to MQTT Listener"
version: "1.0"
slug: "udp_listener"
description: "Empfängt UDP-Daten und sendet sie an MQTT"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
host_network: true
options: {}
schema: {}
